---
- name: Install https transport for apt
  package:
    name: apt-transport-https
    state: present
- name: Add an Apt  extra repo
  include_tasks: Install_Debian_repo.yml
  loop: "{{ dalibo_postgres_debian_repo }}"
