---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  vars:
    postgres_pckg_base_name: "postgresql"
  tasks:
    - name: "Include var file"
      include_vars: "vars/{{ ansible_distribution }}.yml"

    - name: "Check postgres 10 and 12 package status"
      package:
        name: "{{ installed_packages }}"
        state: present
      check_mode: yes
      register: status_installed_packages

    - name: "Test postgres 10 and 12 package are installed"
      assert:
        that:
          - not status_installed_packages.changed

    - name: "Check postgres 13 package status"
      package:
        name: "{{ not_installed_packages }}"
        state: present
      check_mode: yes
      register: status_not_installed_packages

    - name: "Test postgres 13 package is installed"
      assert:
        that:
          - status_not_installed_packages.changed
