---
- name: Install designated repository.
  dnf:
    name: "{{ item.repo_rpm_install }}"
    state: present
    disable_gpg_check: yes
  loop: "{{ dalibo_postgres_redhat_repo }}"

- name: Disable default postgresql module
  blockinfile:
    path: /etc/dnf/modules.d/postgresql.module
    create: yes
    block: |
      [postgresql]
      state=disabled
      name=postgresql
      stream=
      profiles=
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
